# model
model_name: klue/bert-base

# data
train_path: ../dataset/train/v1/train.csv
dev_path: ../dataset/train/v1/dev.csv
predict_path: ../dataset/test/test_data.csv

# seed
seed: 42

# train
output_dir: ./results  # output directory
save_total_limit: 5  # number of total save model.
save_steps: 200  # model saving step. eval step의 배수여야 함
num_train_epochs: 10  # total number of training epochs
learning_rate: 5e-5  # learning_rate
per_device_train_batch_size: 64  # batch size per device during training
per_device_eval_batch_size: 16  # batch size for evaluation
warmup_steps: 200  # number of warmup steps for learning rate scheduler
weight_decay: 0.01  # strength of weight decay
logging_dir: ./logs  # directory for storing logs
logging_steps: 100  # log saving step.
evaluation_strategy: steps  # evaluation strategy to adopt during training
                            # `no`: No evaluation during training.
                            # `steps`: Evaluate every `eval_steps`.
                            # `epoch`: Evaluate every end of epoch.
eval_steps: 200  # evaluation step.
load_best_model_at_end: True

# save
save_path: ./best_model

# wandb
run_name: v1_new_tokenizer
project_name: klue