# model
model_name: klue/bert-base

# data
train_path: ../dataset/train/train_90_PER.csv
dev_path: ../dataset/dev/dev_10_PER.csv
predict_path: ../dataset/test/test_PER.csv

# seed
seed: 42

# train
output_dir: ./results  # output directory
save_total_limit: 5  # number of total save model.
save_steps: 300  # model saving step.
num_train_epochs: 10  # total number of training epochs
learning_rate: 1e-6  # learning_rate
per_device_train_batch_size: 16  # batch size per device during training
per_device_eval_batch_size: 16  # batch size for evaluation
warmup_steps: 0  # number of warmup steps for learning rate scheduler
weight_decay: 0.01  # strength of weight decay
logging_dir: ./logs  # directory for storing logs
logging_steps: 100  # log saving step.
evaluation_strategy: steps  # evaluation strategy to adopt during training
                            # `no`: No evaluation during training.
                            # `steps`: Evaluate every `eval_steps`.
                            # `epoch`: Evaluate every end of epoch.
type: PER # PER or ORG
eval_steps: 300  # evaluation step.
load_best_model_at_end: True

# inference
inference_model_name: PER-5.396825396825397-'micro f1 score'-65.3688524590164

# save
save_path: ./model/per

# wandb
run_name: per
project_name: klue