# model
model_name: klue/bert-base

# data
train_path: ../dataset/train/train_js.csv
dev_path: ../dataset/dev/dev_js.csv
predict_path: ../dataset/test_data.csv

# seed
seed: 42

# train
output_dir: ./results/bert  # output directory
save_total_limit: 1  # number of total save model.
save_steps: 1000  # model saving step.
num_train_epochs: 10  # total number of training epochs
learning_rate: 1e-5  # learning_rate
per_device_train_batch_size: 16  # batch size per device during training
per_device_eval_batch_size: 16  # batch size for evaluation
warmup_steps: 200  # number of warmup steps for learning rate scheduler
weight_decay: 0.01  # strength of weight decay
logging_dir: ./logs  # directory for storing logs
logging_steps: 100  # log saving step.
evaluation_strategy: steps  # evaluation strategy to adopt during training
                            # `no`: No evaluation during training.
                            # `steps`: Evaluate every `eval_steps`.
                            # `epoch`: Evaluate every end of epoch.
eval_steps: 1000  # evaluation step.
load_best_model_at_end: True

# lr scheduler
lr_scheduler_step_size: 457
lr_scheduler_gamma: 0.9

# save
save_path: ./best_model/bert

# wandb
run_name: klue/bert-base
project_name: klue

data_clean:

data_aug:
