# model
model_name: skt/kogpt2-base-v2

# data
train_path: ~/dataset/train/train_90_ksh.csv
dev_path: ~/dataset/dev/dev_10_ksh.csv
predict_path: ~/dataset/test/test_data.csv
shuffle: True
tem: "none" # typed entity marker: "none", "non_punct", "punct"
# tem_punct: False # typed entity marker with punctuation

# seed
seed: 42

# train
output_dir: ./results/skt_kogpt2  # output directory
save_total_limit: 2  # number of total save model.
save_steps: 500  # model saving step.
num_train_epochs: 10  # total number of training epochs
learning_rate: 1e-5  # learning_rate
dropout: 0.2
per_device_train_batch_size: 64  # batch size per device during training
per_device_eval_batch_size: 64  # batch size for evaluation
warmup_steps: 1000  # number of warmup steps for learning rate scheduler
weight_decay: 0.01  # strength of weight decay
logging_dir: ./logs  # directory for storing logs
logging_steps: 10  # log saving step.
evaluation_strategy: steps  # evaluation strategy to adopt during training
                            # `no`: No evaluation during training.
                            # `steps`: Evaluate every `eval_steps`.
                            # `epoch`: Evaluate every end of epoch.
eval_steps: 250  # evaluation step.
load_best_model_at_end: True

# save
save_path: ./best_model/skt_kogpt2

# wandb
run_name: test
project_name: sweep_kogpt2